name: VTK.js Viewer
description: Visualize models using VTK.js
version: 0.1.0
npm:
  dependencies:
    vtk.js: "~7.3.2"
    shader-loader: "~1.3.1"
    worker-loader: "~1.1.1"
    jszip: "~3.1.5"
    base64-arraybuffer: "~0.1.5"
    babel-eslint: "~8.2.5"
    babel-plugin-transform-class-properties: "~6.24.1"
    babel-polyfill: "~6.26.0"
