# Based on CircleCI config from https://github.com/ImageMarkup/isic-archive

version: 2
jobs:
  serverInstall:
    docker:
      - image: girder/girder_test:latest-py2

    working_directory: /home/circleci/project # as $CIRCLE_WORKING_DIRECTORY

    environment:
      - GIRDER_VERSION: 7e6e09ea2de3823e972221cb19ee153f6d08cff1

    steps:
      - run:
          name: Clone Girder
          command: |
            git clone https://github.com/girder/girder.git girder
            git -C girder checkout $GIRDER_VERSION
      - checkout:
          path: girder/plugins/vtk_viewer2

      - run:
          name: Create and activate virtualenv
          command: |
            virtualenv girder_env
            echo "source $CIRCLE_WORKING_DIRECTORY/girder_env/bin/activate" >> $BASH_ENV
      - run:
          name: Create cache key
          command: cat girder/setup.py girder/requirements-dev.txt | sha512sum > venv-req-hash.txt
      - restore_cache:
          key: venv-{{ arch }}-{{ checksum "venv-req-hash.txt" }}
      - run:
          name: Install Girder
          command: |
            pip install --upgrade --editable . --requirement requirements-dev.txt
          # pytest_girder requires that install be run from this directory
          working_directory: girder
      - run:
          name: Install vtk_viewer2
          command: girder-install plugin girder/plugins/vtk_viewer2
    #   - run:
    #       name: Install coverage client
    #       command: pip install --upgrade codecov
    #   - save_cache:
    #       paths: girder_env
    #       key: venv-{{ arch }}-{{ checksum "venv-req-hash.txt" }}

      - run:
          name: Create Girder build directory
          command: mkdir girder_build
      - run:
          name: Run CMake
          command: |
            cmake -DPYTHON_VERSION:STRING=2.7 -DRUN_CORE_TESTS:BOOL=OFF -DTEST_PLUGINS:STRING="vtk_viewer2" $CIRCLE_WORKING_DIRECTORY/girder
            make
          working_directory: girder_build

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - girder
            - girder_build
            - girder_env

  webBuild_webTest:
    docker:
      - image: girder/girder_test:latest-py2
      #- image: circleci/mongo:3.6-ram
      #  command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/dev/shm/mongo"]

    working_directory: /home/circleci/project

    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Activate virtualenv
          command: echo "source $CIRCLE_WORKING_DIRECTORY/girder_env/bin/activate" >> $BASH_ENV

      - restore_cache:
          key: npm-{{ arch }}-{{ checksum "girder/package.json" }}-{{ checksum "girder/plugins/vtk_viewer2/plugin.yml" }}
      - run:
          name: Build Girder web client
          command: girder-install web --dev --plugins=vtk_viewer2
          environment:
            - npm_config_cache: /home/circleci/project/npm_cache
      - save_cache:
          paths: npm_cache
          key: npm-{{ arch }}-{{ checksum "girder/package.json" }}-{{ checksum "girder/plugins/vtk_viewer2/plugin.yml" }}

      - run:
          name: Run CTest
          command: ctest -VV -L girder_browser -E js_coverage
          working_directory: girder_build

workflows:
  version: 2
  test_all:
    jobs:
      - serverInstall
      - webBuild_webTest:
          requires:
            - serverInstall
